name: 'Build And Publish Images'
description: 'Builds and publishes images with pack'
inputs:
  version:
    description: 'dataflow version'
    required: true
  dockerhub-username:
    description: 'dockerhub username'
    required: true
  dockerhub-password:
    description: 'dockerhub password'
    required: true
runs:
  using: "composite"
  steps:
  - name: Install pack
    uses: jvalkeal/build-zoo-handler@v0.0.4
    with:
      pack-version: 0.18.0
  - name: Build Images
    env:
      TAG: ${{ inputs.version }}
    shell: bash
    run: |
      for v in 8 11 17
      do
        pack build \
          --path spring-cloud-skipper-server/target/spring-cloud-skipper-server-$TAG.jar \
          --builder gcr.io/paketo-buildpacks/builder:base \
          --env BP_JVM_VERSION=$v springcloud/spring-cloud-skipper-server:$TAG-jdk$v
      done

  # docker hub login
  - uses: docker/login-action@v1
    with:
      username: ${{ inputs.dockerhub-username }}
      password: ${{ inputs.dockerhub-password }}

  # push images
  - name: Push images
    env:
      TAG: ${{ inputs.version }}
    shell: bash
    run: |
      docker tag springcloud/spring-cloud-skipper-server:$TAG-jdk11 springcloud/spring-cloud-skipper-server:$TAG
      for v in 8 11 17
      do
        docker push springcloud/spring-cloud-skipper-server:$TAG-jdk$v
      done
      docker push springcloud/spring-cloud-skipper-server:$TAG
